### ISSUE TITLE
When will this become an online subsystem

### ISSUE THREAD

**Issue by XZCendence** [RyroNZ/UE4MasterServer#9]
I am working on a game for xbox and I need this plugin as I currently do not have access to XB live online multiplayer.

**Comment by RyroNZ** [comment]
Now I guess :) Enjoy

**Comment by XZCendence** [comment]
Wow that was quick ok thanks!!

**Comment by XZCendence** [comment]
Is OnlineSubsystemPython restricted to dedicated servers or can I just use the client to host a session and use the MasterServer for the active server lists?

**Comment by RyroNZ** [comment]
It's not restricted to dedicated servers

On Dec 18, 2019 6:58 AM, XZCendence <notifications@github.com> wrote:

Is OnlineSubsystemPython restricted to dedicated servers or can I just use the client to host a session and use the MasterServer for the active server lists?

**Comment by XZCendence** [comment]
How would I configure a "domain" for the server instead of an IP and port. Would I just use some DDNS and enter the domain address in the client config for the server address?

**Comment by RyroNZ** [comment]
You use a domain provider (I use namecheap) and you configure an A record pointing to your ip. After waiting some time (usually 5-10min) you can see the ip on that domain
Hope that helps.

On Dec 22, 2019 6:41 PM, XZCendence <notifications@github.com> wrote:

How would I configure a "domain" for the server instead of an IP and port. Would I just use some DDNS and enter the domain address in the client config for the server address?

**Comment by RyroNZ** [comment]
Another thing, you should be using a provider to host your server such as digital ocean and you shouldn't host it on you own equipment as that will never be reliable enough for a video game.

On Dec 22, 2019 6:41 PM, XZCendence <notifications@github.com> wrote:

How would I configure a "domain" for the server instead of an IP and port. Would I just use some DDNS and enter the domain address in the client config for the server address?
